### ISSUE TITLE
Access rights issues and themes

### ISSUE THREAD

**Issue by Exiknox** [bludit/docker#7]
Hello, 

Before I detail my problems, I would like to thank you for the work you have done!

I currently have two problems.

The first concerns access rights to the volume. When I create a container with a volume and then try to connect to the website, I face an error that tells me:
Writing test failure, check directory "bl-content" permissions.

I think this error is due to the fact that nginx is not installed on my machine and therefore the user and group used by your dockerfile do not exist.

The second problem concerns the themes. I noticed that it was not possible to create a volume containing the themes. It's a feature that interests me and I think you just have to do the same steps on bl-themes as on bl-content so that you can access it from a volume.

I hope to hear from you soon because I really want to deploy my blog using this great tool!

Thank you in advance.

My docker-compose file:
```yml
version: '3.3'

services:
   myblog:
     image: bludit/docker:latest
     volumes:
       - ./content:/usr/share/nginx/html/bl-content
     restart: always
     ports: 
       - 8080:80
```
